//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperationInMVC.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [Required(ErrorMessage = "Xin nhập tên nhân viên")]
        [Display(Name = "Tên nhân viên")]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage = "Xin nhập tên nhân viên")]
        [Display(Name = "Lương nhân viên")]
        public Nullable<decimal> EmployeeSalary { get; set; }
        [Display(Name = "Địa chỉ")]
        public string EmployeeCity { get; set; }
        [Required(ErrorMessage = "Xin nhập số điện thoại")]
        [Phone]
        [Display(Name = "Số điện thoại")]
        public string EmployeePhone { get; set; }
        [Required(ErrorMessage = "Xin nhập ngày bắt đầu họp đồng")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Ngày bắt đầu")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [Required(ErrorMessage = "Xin nhập ngày kết thúc họp đồng")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Ngày kết thúc")]
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
